[general]
icao = "VOMF"
fir = "VOMF"
center = [12.95, 77.64]
magnetic_variation = 0.0

[data.kml]
type = "kml"
path = "."
source = "VOMF.kml"

[output]
format = "euroscope"

[profiles.default]
data = ["kml"]

[[profiles.default.maps]]
map = "VOMF_TWR"
target = "VOMF_TWR.ese"
layers = [
  "Runways",
  "Taxiways",
  "Aprons",
  "Hold Short"
]
