[general]
icao = "VOMF"
fir = "VOMF"
center = [12.95, 77.64]
magnetic_variation = 1.0

[data.kml]
type = "kml"
path = "."
source = "VOMF.kml"

[output]
format = "euroscope"

[[profiles]]
name = "default"
data = ["kml"]

[[maps]]
profile = "default"
name = "VOMF_TWR"
layers = [
  "Runways",
  "Taxiways",
  "Aprons",
  "Hold Short"
]
