name: Build EuroScope maps

on:
  workflow_dispatch:

jobs:
  build-maps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MapBuilder
        uses: vatger-nav/mapbuilder@main
